name: ion_networks
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - numpy
  - numexpr
  - matplotlib
  - PySimpleGUI
  - matplotlib
  - pandas
  - click
  - scipy
  - scikit-learn
  - h5py
  - pyteomics
  - numba
  - ipykernel
  - pip:
    - pyqt5-sip
    - pyqtwebengine
    - tables
    - ms2pip
